#!/bin/bash
ssh cloud1 "rm -rf /home/steffeng/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud2 "rm -rf /home/steffeng/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud3 "rm -rf /home/steffeng/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud4 "rm -rf /home/steffeng/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud5 "rm -rf /home/steffeng/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud6 "rm -rf /home/steffeng/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud7 "rm -rf /home/steffeng/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud9 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud10 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud11 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud12 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud13 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud14 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud15 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud16 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud17 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
ssh cloud18 "rm -rf /opt/hop/hadoop-2.0.4-alpha/hdfs/datanode/*"
